version: '3'
services:
  hackaton:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: hackaton
    hostname: hackaton
    image: hackaton
    stdin_open: true
    tty: true
    volumes:
      - ${HOME}/Documents/Projects/k8s/root:/root
      - ${HOME}/Documents/Projects/k8s/repo:/source
      - ${HOME}/Documents/Projects/k8s/private:/private
      - ${HOME}/.kube/config:/root/.kube/config
      # change desired paths below
      #- /home/geising/az/root:/root
      #- /home/geising/ING/terraforming:/data
    #environment:
      # - ${TF_VAR_store_acr_name}
      # - ${TF_VAR_store_acr_password}
      # - ${TF_VAR_store_acr_url}
