version: '3'
services:
  hackaton:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: hackaton
    hostname: hackaton
    image: hackaton
    stdin_open: true
    network_mode: host
    tty: true
    volumes:
      - ${HOME}/Documents/hackaton/root:/root
      - ${HOME}/Documents/hackaton/repo:/source
      - ${HOME}/Documents/hackaton/private:/private
      - ${HOME}/.kube/:/root/.kube/
    #environment:
      # - ${TF_VAR_store_acr_name}
      # - ${TF_VAR_store_acr_password}
      # - ${TF_VAR_store_acr_url}
